# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"/\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"@\n\x04Post\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x0c\n\x04tags\x18\x04 \x03(\t\"\x10\n\x0eGetUserRequest\"\x1f\n\x0fGetUserResponse\x12\x0c\n\x04user\x18\x01 \x01(\t\"0\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"%\n\x12\x43reateUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"A\n\x11UpdateUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"\"\n\x12UpdateUserResponse\x12\x0c\n\x04User\x18\x01 \x01(\t\"$\n\x11\x44\x65leteUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"%\n\x12\x44\x65leteUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xe8\x01\n\x0bUserService\x12.\n\x07GetUser\x12\x0f.GetUserRequest\x1a\x10.GetUserResponse\"\x00\x12\x37\n\nCreateUser\x12\x12.CreateUserRequest\x1a\x13.CreateUserResponse\"\x00\x12\x37\n\nUpdateUser\x12\x12.UpdateUserRequest\x1a\x13.UpdateUserResponse\"\x00\x12\x37\n\nDeleteUser\x12\x12.DeleteUserRequest\x1a\x13.DeleteUserResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=14
  _globals['_USER']._serialized_end=61
  _globals['_POST']._serialized_start=63
  _globals['_POST']._serialized_end=127
  _globals['_GETUSERREQUEST']._serialized_start=129
  _globals['_GETUSERREQUEST']._serialized_end=145
  _globals['_GETUSERRESPONSE']._serialized_start=147
  _globals['_GETUSERRESPONSE']._serialized_end=178
  _globals['_CREATEUSERREQUEST']._serialized_start=180
  _globals['_CREATEUSERREQUEST']._serialized_end=228
  _globals['_CREATEUSERRESPONSE']._serialized_start=230
  _globals['_CREATEUSERRESPONSE']._serialized_end=267
  _globals['_UPDATEUSERREQUEST']._serialized_start=269
  _globals['_UPDATEUSERREQUEST']._serialized_end=334
  _globals['_UPDATEUSERRESPONSE']._serialized_start=336
  _globals['_UPDATEUSERRESPONSE']._serialized_end=370
  _globals['_DELETEUSERREQUEST']._serialized_start=372
  _globals['_DELETEUSERREQUEST']._serialized_end=408
  _globals['_DELETEUSERRESPONSE']._serialized_start=410
  _globals['_DELETEUSERRESPONSE']._serialized_end=447
  _globals['_USERSERVICE']._serialized_start=450
  _globals['_USERSERVICE']._serialized_end=682
# @@protoc_insertion_point(module_scope)
